{
  "openapi": "3.0.0",
  "info": {
    "title": "Billing",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "https://api.counterbalance.io",
      "description": "Production API"
    }
  ],
  "paths": {
    "/v1/billing/account": {
      "get": {
        "summary": "Get Billing Account",
        "tags": [
          "Billing Account"
        ],
        "responses": {
          "200": {
            "$ref": "#/components/responses/200-GET-Billing-Account"
          }
        },
        "operationId": "get-billing-account",
        "security": [
          {
            "Bearer Token": []
          }
        ],
        "description": "Retrieve tenant billing account\n\n**Required Permissions:** `*`,`billing:*`,`billing:account:*`,`billing:account:read`"
      },
      "post": {
        "summary": "Create Billing Account",
        "operationId": "create-billing-account",
        "responses": {
          "201": {
            "description": "Created"
          }
        },
        "description": "Create tenant billing account\n\n**Required Permissions:** `*`,`billing:*`,`billing:account:*`,`billing:account:create`",
        "tags": [
          "Billing Account"
        ],
        "security": [
          {
            "Bearer Token": []
          }
        ]
      },
      "parameters": [],
      "patch": {
        "summary": "Update Billing Account",
        "operationId": "update-billing-account",
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "tags": [
          "Billing Account"
        ],
        "description": "Update tenant billing account\n\n**Required Permissions:** `*`,`billing:*`,`billing:account:*`,`billing:account:update`",
        "security": [
          {
            "Bearer Token": []
          }
        ]
      },
      "delete": {
        "summary": "Delete Billing Account",
        "operationId": "delete-billing-account",
        "responses": {
          "204": {
            "description": "No Content"
          }
        },
        "security": [
          {
            "Bearer Token": []
          }
        ],
        "tags": [
          "Billing Account"
        ],
        "description": "Delete/remove tenant billing account\n\n**Required Permissions:** `*`,`billing:*`,`billing:account:*`,`billing:account:delete`"
      }
    },
    "/v1/billing/account/sources": {
      "get": {
        "summary": "List Payment Sources",
        "responses": {
          "200": {
            "$ref": "#/components/responses/200-GET-Payment-Sources"
          }
        },
        "operationId": "list-payment-sources",
        "description": "List payment sources\n\n**Required Permissions:** `*`,`billing:*`,`billing:sources:*`,`billing:sources:read`",
        "security": [
          {
            "Bearer Token": []
          }
        ],
        "tags": [
          "Payment Source"
        ]
      },
      "parameters": [],
      "post": {
        "summary": "Create Payment Source",
        "operationId": "create-payment-source",
        "responses": {
          "201": {
            "description": "Created"
          }
        },
        "description": "Create a new payment source\n\n**Required Permissions:** `*`,`billing:*`,`billing:sources:*`,`billing:sources:create`",
        "security": [
          {
            "Bearer Token": []
          }
        ],
        "tags": [
          "Payment Source"
        ]
      }
    },
    "/v1/billing/account/sources/{sourceId}": {
      "parameters": [
        {
          "$ref": "#/components/parameters/sourceId"
        }
      ],
      "get": {
        "summary": "Get Payment Source",
        "responses": {
          "200": {
            "$ref": "#/components/responses/200-GET-Payment-Source"
          }
        },
        "operationId": "get-payment-source",
        "description": "Retrieve a payment source\n\n**Required Permissions:** `*`,`billing:*`,`billing:sources:*`,`billing:sources:read`",
        "security": [
          {
            "Bearer Token": []
          }
        ],
        "tags": [
          "Payment Source"
        ]
      },
      "patch": {
        "summary": "Update Payment Source",
        "operationId": "update-payment-source",
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "tags": [
          "Payment Source"
        ],
        "description": "Update a payment source\n\n**Required Permissions:** `*`,`billing:*`,`billing:sources:*`,`billing:sources:update`",
        "security": [
          {
            "Bearer Token": []
          }
        ]
      },
      "delete": {
        "summary": "Delete Payment Source",
        "operationId": "delete-payment-source",
        "responses": {
          "204": {
            "description": "No Content"
          }
        },
        "tags": [
          "Payment Source"
        ],
        "security": [
          {
            "Bearer Token": []
          }
        ],
        "description": "Delete a payment source\n\n**Required Permissions:** `*`,`billing:*`,`billing:sources:*`,`billing:sources:delete`"
      }
    },
    "/v1/billing/subscription": {
      "get": {
        "summary": "List Subscriptions",
        "tags": [
          "Subscription"
        ],
        "responses": {
          "200": {
            "$ref": "#/components/responses/200-GET-Subscriptions"
          }
        },
        "operationId": "list-subscriptions",
        "security": [
          {
            "Bearer Token": []
          }
        ],
        "description": "Retrieve a list of subscriptions\n\n**Required Permissions:** `*`,`billing:*`,`billing:subscription:*`,`billing:subscription:read`"
      },
      "post": {
        "summary": "Create Subscription",
        "operationId": "create-subscription",
        "responses": {
          "201": {
            "description": "Created"
          }
        },
        "security": [
          {
            "Bearer Token": []
          }
        ],
        "description": "Create a new subscription\n\n**Required Permissions:** `*`,`billing:*`,`billing:subscription:*`,`billing:subscription:create`",
        "tags": [
          "Subscription"
        ]
      }
    },
    "/v1/billing/subscription/{subscriptionId}": {
      "parameters": [
        {
          "$ref": "#/components/parameters/subscriptionId"
        }
      ],
      "get": {
        "summary": "Get Subscription",
        "tags": [
          "Subscription"
        ],
        "responses": {
          "200": {
            "$ref": "#/components/responses/200-GET-Subscription"
          }
        },
        "operationId": "get-subscription",
        "security": [
          {
            "Bearer Token": []
          }
        ],
        "description": "Retrieve a subscription\n\n**Required Permissions:** `*`,`billing:*`,`billing:subscription:*`,`billing:subscription:read`"
      },
      "patch": {
        "summary": "Update Subscription",
        "operationId": "update-subscription",
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "description": "Update a subscription\n\n**Required Permissions:** `*`,`billing:*`,`billing:subscription:*`,`billing:subscription:update`",
        "security": [
          {
            "Bearer Token": []
          }
        ],
        "tags": [
          "Subscription"
        ]
      },
      "delete": {
        "summary": "Delete Subscription",
        "operationId": "delete-subscription",
        "responses": {
          "204": {
            "description": "No Content"
          }
        },
        "description": "Delete a subscription\n\n**Required Permissions:** `*`,`billing:*`,`billing:subscription:*`,`billing:subscription:delete`",
        "security": [
          {
            "Bearer Token": []
          }
        ],
        "tags": [
          "Subscription"
        ]
      }
    },
    "/v1/subscription/{subscriptionId}/upcoming-invoice": {
      "parameters": [
        {
          "$ref": "#/components/parameters/subscriptionId"
        }
      ],
      "get": {
        "summary": "Get Upcoming Invoice",
        "tags": [
          "Subscription"
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "operationId": "get-subscription-upcoming-invoice",
        "description": "Get upcoming invoice\n\n**Required Permissions:** `*`,`billing:*`,`billing:invoice:*`,`billing:invoice:read`",
        "security": [
          {
            "Bearer Token": []
          }
        ]
      }
    },
    "/v1/billing/invoice": {
      "get": {
        "summary": "List Invoices",
        "tags": [
          "Invoice"
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "operationId": "list-invoices",
        "description": "List invoices\n\n**Required Permissions:** `*`,`billing:*`,`billing:invoice:*`,`billing:invoice:read`",
        "security": [
          {
            "Bearer Token": []
          }
        ]
      }
    },
    "/v1/billing/invoice/{invoiceId}": {
      "parameters": [
        {
          "$ref": "#/components/parameters/invoiceId"
        }
      ],
      "get": {
        "summary": "Get Invoice",
        "tags": [
          "Invoice"
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "operationId": "get-invoice",
        "security": [
          {
            "Bearer Token": []
          }
        ],
        "description": "Retrieve an invoice\n\n**Required Permissions:** `*`,`billing:*`,`billing:invoice:*`,`billing:invoice:read`"
      }
    }
  },
  "components": {
    "schemas": {
      "Billing-Account-Object": {
        "description": "",
        "type": "object",
        "x-examples": {},
        "properties": {
          "id": {
            "type": "string",
            "readOnly": true
          },
          "created": {
            "type": "string",
            "minLength": 1
          },
          "currency": {
            "type": "string",
            "minLength": 1
          },
          "description": {
            "type": "string"
          },
          "subscriptions": {
            "type": "object",
            "properties": {
              "count": {
                "type": "integer",
                "readOnly": true
              },
              "index": {
                "type": "array",
                "uniqueItems": true,
                "items": {
                  "type": "string",
                  "format": "uuid",
                  "readOnly": true
                }
              },
              "data": {
                "type": "array",
                "uniqueItems": true,
                "minItems": 1,
                "items": {
                  "$ref": "#/components/schemas/Subscription-Object"
                }
              }
            }
          },
          "sources": {
            "type": "object",
            "properties": {
              "count": {
                "type": "integer"
              },
              "index": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "data": {
                "type": "array",
                "uniqueItems": true,
                "minItems": 1,
                "items": {
                  "$ref": "#/components/schemas/Payment-Source-Object"
                }
              }
            }
          },
          "default_source": {
            "type": "string",
            "minLength": 1
          },
          "invoicing": {
            "type": "object",
            "properties": {
              "prefix": {
                "type": "string",
                "minLength": 1
              },
              "next_sequence": {
                "type": "integer",
                "readOnly": true
              }
            }
          },
          "balance": {
            "type": "number",
            "readOnly": true
          },
          "delinquent": {
            "type": "boolean",
            "readOnly": true
          },
          "billing": {
            "type": "object",
            "properties": {
              "company": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "minLength": 1
                  },
                  "email": {
                    "type": "string",
                    "minLength": 1
                  },
                  "phone": {
                    "type": "string",
                    "minLength": 1
                  }
                }
              },
              "address": {
                "type": "object",
                "properties": {
                  "lines": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "city": {
                    "type": "string",
                    "minLength": 1
                  },
                  "state": {
                    "type": "string",
                    "minLength": 1
                  },
                  "postcode": {
                    "type": "string",
                    "minLength": 1
                  }
                }
              }
            }
          }
        },
        "title": "Billing Account Object",
        "x-tags": [
          "Billing Account"
        ]
      },
      "Subscription-Object": {
        "description": "",
        "type": "object",
        "x-examples": {},
        "title": "Subscription Object",
        "x-tags": [
          "Subscription"
        ],
        "properties": {
          "id": {
            "type": "string",
            "example": "sub_K5p1RfYtyRnfMG"
          },
          "created": {
            "type": "string",
            "example": "2021-08-23T13:40:18+0000"
          },
          "start_date": {
            "type": "string",
            "minLength": 1,
            "format": "date-time",
            "example": "2021-08-23T13:40:18+0000",
            "readOnly": true
          },
          "status": {
            "type": "string"
          },
          "billing": {
            "type": "object",
            "properties": {
              "cycle_anchor": {
                "type": "string",
                "minLength": 1
              },
              "collection_method": {
                "type": "string",
                "minLength": 1
              },
              "paused": {
                "type": "boolean"
              },
              "pause_collection": {
                "type": "object",
                "nullable": true
              },
              "current_period": {
                "type": "object",
                "properties": {
                  "start": {
                    "type": "string",
                    "format": "date-time",
                    "readOnly": true
                  },
                  "end": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2021-08-23T13:40:17+0000",
                    "readOnly": true
                  }
                }
              },
              "default_source": {
                "type": "string",
                "nullable": true
              }
            }
          },
          "days_until_due": {
            "type": "integer",
            "nullable": true
          },
          "latest_invoice": {
            "type": "string",
            "minLength": 1
          },
          "items": {
            "type": "object",
            "properties": {
              "count": {
                "type": "number"
              },
              "index": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "data": {
                "type": "array",
                "uniqueItems": true,
                "minItems": 1,
                "items": {
                  "$ref": "#/components/schemas/Subscription-Item-Object"
                }
              }
            }
          }
        }
      },
      "Payment-Source-Object": {
        "description": "",
        "type": "object",
        "x-examples": {},
        "title": "Payment Source Object",
        "x-tags": [
          "Payment Source"
        ],
        "properties": {
          "id": {
            "type": "string",
            "readOnly": true
          },
          "nickname": {
            "type": "string"
          },
          "cardholder_name": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "brand": {
            "type": "string"
          },
          "funding": {
            "type": "string",
            "readOnly": true
          },
          "last4": {
            "type": "string",
            "readOnly": true
          },
          "expiration": {
            "type": "object",
            "properties": {
              "month": {
                "type": "number"
              },
              "year": {
                "type": "number"
              }
            }
          },
          "fingerprint": {
            "type": "string",
            "readOnly": true
          },
          "cvc_check": {
            "type": "string",
            "readOnly": true
          }
        }
      },
      "Invoice-Object": {
        "title": "Invoice Object",
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          }
        },
        "x-tags": [
          "Invoice"
        ]
      },
      "Subscription-Item-Object": {
        "description": "",
        "type": "object",
        "x-examples": {},
        "title": "Subscription Item Object",
        "x-tags": [
          "Subscription"
        ],
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          },
          "created": {
            "type": "string",
            "minLength": 1
          },
          "product": {
            "type": "string",
            "minLength": 1
          },
          "plan": {
            "type": "string",
            "minLength": 1
          },
          "price": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string",
                "minLength": 1
              },
              "scheme": {
                "type": "string",
                "minLength": 1
              },
              "unit_amount": {
                "type": "number"
              },
              "frequency": {
                "type": "string",
                "minLength": 1
              },
              "interval": {
                "type": "number"
              }
            }
          },
          "usage_type": {
            "type": "string",
            "minLength": 1
          },
          "quantity": {
            "type": "number"
          },
          "name": {}
        }
      }
    },
    "securitySchemes": {
      "Bearer Token": {
        "type": "http",
        "scheme": "bearer"
      }
    },
    "parameters": {
      "sourceId": {
        "name": "sourceId",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string"
        },
        "description": "A valid payment source ID"
      },
      "invoiceId": {
        "name": "invoiceId",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string"
        },
        "description": "A valid invoice ID"
      },
      "subscriptionId": {
        "name": "subscriptionId",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string"
        },
        "description": "A valid subscription ID"
      }
    },
    "requestBodies": {
      "Create-Billing-Account": {
        "content": {
          "application/json": {
            "schema": {
              "type": "object"
            }
          }
        }
      },
      "Create-Payment-Source": {
        "content": {
          "application/json": {
            "schema": {
              "type": "object"
            }
          }
        }
      },
      "Update-Payment-Source": {
        "content": {
          "application/json": {
            "schema": {
              "type": "object"
            }
          }
        }
      },
      "Update-Billing-Account": {
        "content": {
          "application/json": {
            "schema": {
              "type": "object"
            }
          }
        }
      }
    },
    "responses": {
      "200-GET-Billing-Account": {
        "description": "Ok",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Billing-Account-Object"
            },
            "examples": {
              "Response": {
                "$ref": "#/components/examples/Billing-Account"
              }
            }
          }
        }
      },
      "200-GET-Payment-Sources": {
        "description": "Ok",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "count": {
                  "type": "integer"
                },
                "index": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                "": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Payment-Source-Object"
                  }
                }
              }
            },
            "examples": {}
          }
        }
      },
      "200-GET-Payment-Source": {
        "description": "Ok",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Payment-Source-Object"
            },
            "examples": {
              "Response": {
                "$ref": "#/components/examples/Payment-Source"
              }
            }
          }
        }
      },
      "404-GET-Payment-Source-Not-Found": {
        "description": "Not Found",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "../models/Error-Response.v1.yaml"
            },
            "examples": {
              "Response": {
                "value": {
                  "error": {
                    "message": "string",
                    "console": "string",
                    "code": 0
                  },
                  "logging_hash": "string"
                }
              }
            }
          }
        }
      },
      "200-GET-Subscriptions": {
        "description": "Ok",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "count": {
                  "type": "integer"
                },
                "index": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                "data": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Subscription-Object"
                  }
                }
              }
            }
          }
        }
      },
      "200-GET-Subscription": {
        "description": "Ok",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Subscription-Object"
            },
            "examples": {
              "Response": {
                "$ref": "#/components/examples/Subscription"
              }
            }
          }
        }
      }
    },
    "examples": {
      "Billing-Account": {
        "value": {
          "id": "cus_Gr2tvkQK7Yrujz",
          "created": "2020-03-05T14:36:12+0000",
          "currency": "usd",
          "description": "",
          "subscriptions": {
            "count": 2,
            "index": [
              "...",
              "..."
            ],
            "data": [
              {
                "...": null
              },
              {
                "...": null
              }
            ]
          },
          "sources": {
            "count": 2,
            "index": [
              "...",
              "..."
            ],
            "data": [
              {
                "...": null
              },
              {
                "...": null
              }
            ]
          },
          "default_source": "card_1GJKp7J5K0z3IHPXD1ciFRwt",
          "invoicing": {
            "prefix": "F2A29AE0",
            "next_sequence": 38
          },
          "balance": 0,
          "delinquent": false,
          "billing": {
            "company": {
              "name": "Peterbalance Architecture",
              "email": "alexw@peterbalance.com",
              "phone": "2069030575"
            },
            "address": {
              "lines": [
                "2333 3rd Ave",
                ""
              ],
              "city": "Seattle",
              "state": "WA",
              "postcode": "98121"
            }
          }
        }
      },
      "Payment-Source": {
        "value": {
          "id": "card_1GJKp7J5K0z3IHPXD1ciFRwt",
          "nickname": "Default Card",
          "cardholder_name": "Taylor Vick",
          "type": "card",
          "brand": "American Express",
          "funding": "credit",
          "last4": "0005",
          "expiration": {
            "month": 9,
            "year": 2022
          },
          "fingerprint": "o19iQvRGhtvzbzRm",
          "cvc_check": "pass"
        }
      },
      "Subscription": {
        "value": {
          "id": "sub_K5UfhyQEJEfg2R",
          "created": "2021-08-22T16:37:31+0000",
          "start_date": "2021-08-22T16:37:31+0000",
          "status": "active",
          "billing": {
            "cycle_anchor": "2021-08-22T16:37:31+0000",
            "collection_method": "send_invoice",
            "paused": false,
            "pause_collection": null,
            "current_period": {
              "start": "2022-01-22T16:37:31+0000",
              "end": "2022-02-22T16:37:31+0000"
            },
            "default_source": null
          },
          "days_until_due": 30,
          "latest_invoice": "in_1KKmbuJ5K0z3IHPX0CUko1Ti",
          "items": {
            "count": 1,
            "index": [
              "..."
            ],
            "data": [
              {
                "...": null
              }
            ]
          }
        }
      },
      "Subscription-Item": {
        "value": {
          "id": "si_K5p1H0XbUF2OF0",
          "created": "2021-08-23T13:40:18+0000",
          "product": "prod_JrQ5bpNpFpJMIH",
          "plan": "price_1JDhFhJ5K0z3IHPXQmXXDlZJ",
          "price": {
            "id": "price_1JDhFhJ5K0z3IHPXQmXXDlZJ",
            "scheme": "per_unit",
            "unit_amount": 200,
            "frequency": "month",
            "interval": 1
          },
          "usage_type": "licensed",
          "quantity": 12,
          "name": null
        }
      }
    }
  },
  "tags": [
    {
      "name": "Billing Account"
    },
    {
      "name": "Subscription"
    },
    {
      "name": "Invoice"
    },
    {
      "name": "Payment Source"
    }
  ]
}